### ISSUE TITLE
Wheels for aarch64 platform (AWS Graviton2 arm64)

### ISSUE THREAD

**Issue by thiezn** [rushter/selectolax#81]
Hi, 

Thanks for the great library! Would it be possible to add wheels for the aarch64 platform in future releases? I'm not 100% sure how difficult this would be, but it seems cibuildwheel does support the architecture.

The use case is that this will allow you to easily leverage the library on the new(ish) AWS Lambda Graviton2 architecture arm64. At the moment you have to jump through a few hoops to ensure you build the library for the proper platform. 

## Workaround
The current way to tackle this is to leverage AWS SAM cli using ```sam build --use-container```. To build it properly from an AWS Lambda Layer you have to specify both the compatible architecture and the BuildArchitecture:

```yaml
  LamdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: name-of-layer
      ContentUri: ./src/my-layer
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - arm64
      Metadata:
        BuildMethod: makefile
        BuildArchitecture: arm64
```

Also check this [stackoverflow issue](https://stackoverflow.com/questions/74975839/lambda-selectolax-import-partially-initialized-module-selectolax/75806935#75806935).
